### ISSUE TITLE
How to run mSigHdp (singularity) with singe sample 

### ISSUE THREAD

**Issue by yacai0412** [steverozen/mSigHdp#5]
Hi, I calling snv from _Drosophila melanogaster_  soma cell, I want to extract the mutation signature using singularity container and your demo code test_mSigHdp.R. How to deal with single sample input? Do I need to do bootstrap or other processes?

**Comment by liumoLM** [comment]
Let's discuss this issue over the meeting later. Thank you.

The ticket will be closed.
